enabled = true
sneakToExcavate = false
diagonallyMine = true
maxMinedBlocks = 40
maxMineDistance = 10
autoPickup = true
requiresTool = false
stopBeforeToolBroken = true
stopAfterToolBroken = true
causeToolDamage = true
causePlayerExhaustion = true
exhaustionMultiplier = 1.0
tools = []
groups = []
enableShapes = true
shapeIgnoreIdMismatch = true
asAllowlist = false
blocklistedBlocks = []
